# IDE
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1G
org.gradle.warning.mode=all
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.21.9
yarnMappings=1.21.9+build.1
loaderVersion=0.17.2
# Fabric API
fabricVersion=0.134.0+1.21.9
loomVersion=1.11-SNAPSHOT
# Mod Properties
modVersion=3.0.6-fabric
mavenGroup=com.technicjelle
archivesBaseName=bluemap-offline-player-markers
# Kotlin
systemProp.kotlinVersion=2.1.10
fabricKotlinVersion=1.13.1+kotlin.2.1.10
