# Marker Set Options
# Documentation: https://bluemap.bluecolored.de/wiki/customization/Markers.html#marker-sets
MarkerSetName: "Offline Players"
Toggleable: true
DefaultHidden: false

# By default, this plugin will show everyone who has ever joined the server.
# If you want to show only players who have joined in the last X hours, set this to a number greater than 0.
# If you want to show all players, set this to 0.
# Feel free to use a calculator to convert days to hours: https://www.google.com/search?q=days+to+hours+calculator
ExpireTimeInHours: 0

# If you want to hide players in certain game modes, add them here.
HiddenGameModes:
  - spectator

# If you want to show players who are banned, set this to false.
HideBannedPlayers: true
