name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            target/*.jar
            !target/original-*.jar
